package org.example.microservicenotification.entity;

public enum NotificationType {
  RESERVATION_CREATED,
  RESERVATION_CONFIRMED,
  RESERVATION_CANCELLED,
  RESERVATION_REMINDER,
  PAYMENT_SUCCESS,
  PAYMENT_FAILED,
  PAYMENT_PENDING,
  PAYMENT_REFUND,
  CLUB_ANNOUNCEMENT,
  SYSTEM_ALERT,
  PROMOTIONAL,
  WELCOME_MESSAGE
}
